/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Platform = IDL.Variant({
  'linkedin' : IDL.Null,
  'tiktok' : IDL.Null,
  'twitter' : IDL.Null,
  'instagram' : IDL.Null,
  'facebook' : IDL.Null,
});
export const AddAccountRequest = IDL.Record({
  'refreshToken' : IDL.Text,
  'platform' : Platform,
  'accessToken' : IDL.Text,
  'accountHandle' : IDL.Text,
});
export const AccountId = IDL.Nat;
export const Timestamp = IDL.Int;
export const SocialAccountPublic = IDL.Record({
  'id' : AccountId,
  'createdAt' : Timestamp,
  'platform' : Platform,
  'isActive' : IDL.Bool,
  'accountHandle' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreatePostRequest = IDL.Record({
  'mediaFilename' : IDL.Text,
  'originalCaption' : IDL.Text,
  'mediaBlob' : ExternalBlob,
  'selectedPlatforms' : IDL.Vec(Platform),
});
export const PostId = IDL.Nat;
export const PublishStatus = IDL.Variant({
  'pending' : IDL.Null,
  'publishing' : IDL.Null,
  'success' : IDL.Null,
  'failed' : IDL.Text,
});
export const PlatformResult = IDL.Record({
  'status' : PublishStatus,
  'postUrl' : IDL.Opt(IDL.Text),
  'publishedAt' : IDL.Opt(Timestamp),
  'platform' : Platform,
});
export const PostPublic = IDL.Record({
  'id' : PostId,
  'mediaFilename' : IDL.Text,
  'createdAt' : Timestamp,
  'originalCaption' : IDL.Text,
  'publishStatus' : PublishStatus,
  'updatedAt' : Timestamp,
  'mediaBlob' : ExternalBlob,
  'platformResults' : IDL.Vec(PlatformResult),
  'selectedPlatforms' : IDL.Vec(Platform),
});
export const PlatformCaption = IDL.Record({
  'hashtags' : IDL.Vec(IDL.Text),
  'platform' : Platform,
  'caption' : IDL.Text,
});
export const OptimizationResult = IDL.Record({
  'suggestions' : IDL.Vec(PlatformCaption),
  'generatedAt' : Timestamp,
  'postId' : PostId,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addSocialAccount' : IDL.Func([AddAccountRequest], [SocialAccountPublic], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([CreatePostRequest], [PostPublic], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOptimizationResult' : IDL.Func(
      [PostId],
      [IDL.Opt(OptimizationResult)],
      ['query'],
    ),
  'getPost' : IDL.Func([PostId], [IDL.Opt(PostPublic)], ['query']),
  'getPublishResults' : IDL.Func(
      [PostId],
      [IDL.Vec(PlatformResult)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPosts' : IDL.Func([], [IDL.Vec(PostPublic)], ['query']),
  'listSocialAccounts' : IDL.Func(
      [],
      [IDL.Vec(SocialAccountPublic)],
      ['query'],
    ),
  'optimizeCaption' : IDL.Func([PostId], [OptimizationResult], []),
  'publishPost' : IDL.Func([PostId], [IDL.Vec(PlatformResult)], []),
  'revokeSocialAccount' : IDL.Func([AccountId], [IDL.Bool], []),
  'transformAi' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformPublish' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Platform = IDL.Variant({
    'linkedin' : IDL.Null,
    'tiktok' : IDL.Null,
    'twitter' : IDL.Null,
    'instagram' : IDL.Null,
    'facebook' : IDL.Null,
  });
  const AddAccountRequest = IDL.Record({
    'refreshToken' : IDL.Text,
    'platform' : Platform,
    'accessToken' : IDL.Text,
    'accountHandle' : IDL.Text,
  });
  const AccountId = IDL.Nat;
  const Timestamp = IDL.Int;
  const SocialAccountPublic = IDL.Record({
    'id' : AccountId,
    'createdAt' : Timestamp,
    'platform' : Platform,
    'isActive' : IDL.Bool,
    'accountHandle' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreatePostRequest = IDL.Record({
    'mediaFilename' : IDL.Text,
    'originalCaption' : IDL.Text,
    'mediaBlob' : ExternalBlob,
    'selectedPlatforms' : IDL.Vec(Platform),
  });
  const PostId = IDL.Nat;
  const PublishStatus = IDL.Variant({
    'pending' : IDL.Null,
    'publishing' : IDL.Null,
    'success' : IDL.Null,
    'failed' : IDL.Text,
  });
  const PlatformResult = IDL.Record({
    'status' : PublishStatus,
    'postUrl' : IDL.Opt(IDL.Text),
    'publishedAt' : IDL.Opt(Timestamp),
    'platform' : Platform,
  });
  const PostPublic = IDL.Record({
    'id' : PostId,
    'mediaFilename' : IDL.Text,
    'createdAt' : Timestamp,
    'originalCaption' : IDL.Text,
    'publishStatus' : PublishStatus,
    'updatedAt' : Timestamp,
    'mediaBlob' : ExternalBlob,
    'platformResults' : IDL.Vec(PlatformResult),
    'selectedPlatforms' : IDL.Vec(Platform),
  });
  const PlatformCaption = IDL.Record({
    'hashtags' : IDL.Vec(IDL.Text),
    'platform' : Platform,
    'caption' : IDL.Text,
  });
  const OptimizationResult = IDL.Record({
    'suggestions' : IDL.Vec(PlatformCaption),
    'generatedAt' : Timestamp,
    'postId' : PostId,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addSocialAccount' : IDL.Func(
        [AddAccountRequest],
        [SocialAccountPublic],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([CreatePostRequest], [PostPublic], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOptimizationResult' : IDL.Func(
        [PostId],
        [IDL.Opt(OptimizationResult)],
        ['query'],
      ),
    'getPost' : IDL.Func([PostId], [IDL.Opt(PostPublic)], ['query']),
    'getPublishResults' : IDL.Func(
        [PostId],
        [IDL.Vec(PlatformResult)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPosts' : IDL.Func([], [IDL.Vec(PostPublic)], ['query']),
    'listSocialAccounts' : IDL.Func(
        [],
        [IDL.Vec(SocialAccountPublic)],
        ['query'],
      ),
    'optimizeCaption' : IDL.Func([PostId], [OptimizationResult], []),
    'publishPost' : IDL.Func([PostId], [IDL.Vec(PlatformResult)], []),
    'revokeSocialAccount' : IDL.Func([AccountId], [IDL.Bool], []),
    'transformAi' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformPublish' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };