/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountId = bigint;
export interface AddAccountRequest {
  'refreshToken' : string,
  'platform' : Platform,
  'accessToken' : string,
  'accountHandle' : string,
}
export interface CreatePostRequest {
  'mediaFilename' : string,
  'originalCaption' : string,
  'mediaBlob' : ExternalBlob,
  'selectedPlatforms' : Array<Platform>,
}
export type ExternalBlob = Uint8Array;
export interface OptimizationResult {
  'suggestions' : Array<PlatformCaption>,
  'generatedAt' : Timestamp,
  'postId' : PostId,
}
export type Platform = { 'linkedin' : null } |
  { 'tiktok' : null } |
  { 'twitter' : null } |
  { 'instagram' : null } |
  { 'facebook' : null };
export interface PlatformCaption {
  'hashtags' : Array<string>,
  'platform' : Platform,
  'caption' : string,
}
export interface PlatformResult {
  'status' : PublishStatus,
  'postUrl' : [] | [string],
  'publishedAt' : [] | [Timestamp],
  'platform' : Platform,
}
export type PostId = bigint;
export interface PostPublic {
  'id' : PostId,
  'mediaFilename' : string,
  'createdAt' : Timestamp,
  'originalCaption' : string,
  'publishStatus' : PublishStatus,
  'updatedAt' : Timestamp,
  'mediaBlob' : ExternalBlob,
  'platformResults' : Array<PlatformResult>,
  'selectedPlatforms' : Array<Platform>,
}
export type PublishStatus = { 'pending' : null } |
  { 'publishing' : null } |
  { 'success' : null } |
  { 'failed' : string };
export interface SocialAccountPublic {
  'id' : AccountId,
  'createdAt' : Timestamp,
  'platform' : Platform,
  'isActive' : boolean,
  'accountHandle' : string,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addSocialAccount' : ActorMethod<[AddAccountRequest], SocialAccountPublic>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[CreatePostRequest], PostPublic>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOptimizationResult' : ActorMethod<[PostId], [] | [OptimizationResult]>,
  'getPost' : ActorMethod<[PostId], [] | [PostPublic]>,
  'getPublishResults' : ActorMethod<[PostId], Array<PlatformResult>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listPosts' : ActorMethod<[], Array<PostPublic>>,
  'listSocialAccounts' : ActorMethod<[], Array<SocialAccountPublic>>,
  'optimizeCaption' : ActorMethod<[PostId], OptimizationResult>,
  'publishPost' : ActorMethod<[PostId], Array<PlatformResult>>,
  'revokeSocialAccount' : ActorMethod<[AccountId], boolean>,
  'transformAi' : ActorMethod<[TransformationInput], TransformationOutput>,
  'transformPublish' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];