/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface PostPublic {
    id: PostId;
    mediaFilename: string;
    createdAt: Timestamp;
    originalCaption: string;
    publishStatus: PublishStatus;
    updatedAt: Timestamp;
    mediaBlob: ExternalBlob;
    platformResults: Array<PlatformResult>;
    selectedPlatforms: Array<Platform>;
}
export interface AddAccountRequest {
    refreshToken: string;
    platform: Platform;
    accessToken: string;
    accountHandle: string;
}
export type PostId = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type PublishStatus = {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "publishing";
    publishing: null;
} | {
    __kind__: "success";
    success: null;
} | {
    __kind__: "failed";
    failed: string;
};
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PlatformCaption {
    hashtags: Array<string>;
    platform: Platform;
    caption: string;
}
export interface PlatformResult {
    status: PublishStatus;
    postUrl?: string;
    publishedAt?: Timestamp;
    platform: Platform;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface SocialAccountPublic {
    id: AccountId;
    createdAt: Timestamp;
    platform: Platform;
    isActive: boolean;
    accountHandle: string;
}
export type AccountId = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface CreatePostRequest {
    mediaFilename: string;
    originalCaption: string;
    mediaBlob: ExternalBlob;
    selectedPlatforms: Array<Platform>;
}
export interface OptimizationResult {
    suggestions: Array<PlatformCaption>;
    generatedAt: Timestamp;
    postId: PostId;
}
export enum Platform {
    linkedin = "linkedin",
    tiktok = "tiktok",
    twitter = "twitter",
    instagram = "instagram",
    facebook = "facebook"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addSocialAccount(req: AddAccountRequest): Promise<SocialAccountPublic>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPost(req: CreatePostRequest): Promise<PostPublic>;
    getCallerUserRole(): Promise<UserRole>;
    getOptimizationResult(postId: PostId): Promise<OptimizationResult | null>;
    getPost(postId: PostId): Promise<PostPublic | null>;
    getPublishResults(postId: PostId): Promise<Array<PlatformResult>>;
    isCallerAdmin(): Promise<boolean>;
    listPosts(): Promise<Array<PostPublic>>;
    listSocialAccounts(): Promise<Array<SocialAccountPublic>>;
    optimizeCaption(postId: PostId): Promise<OptimizationResult>;
    publishPost(postId: PostId): Promise<Array<PlatformResult>>;
    revokeSocialAccount(accountId: AccountId): Promise<boolean>;
    transformAi(input: TransformationInput): Promise<TransformationOutput>;
    transformPublish(input: TransformationInput): Promise<TransformationOutput>;
}
import type { AccountId as _AccountId, AddAccountRequest as _AddAccountRequest, CreatePostRequest as _CreatePostRequest, ExternalBlob as _ExternalBlob, OptimizationResult as _OptimizationResult, Platform as _Platform, PlatformCaption as _PlatformCaption, PlatformResult as _PlatformResult, PostId as _PostId, PostPublic as _PostPublic, PublishStatus as _PublishStatus, SocialAccountPublic as _SocialAccountPublic, Timestamp as _Timestamp, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addSocialAccount(arg0: AddAccountRequest): Promise<SocialAccountPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.addSocialAccount(to_candid_AddAccountRequest_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SocialAccountPublic_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSocialAccount(to_candid_AddAccountRequest_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SocialAccountPublic_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPost(arg0: CreatePostRequest): Promise<PostPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(await to_candid_CreatePostRequest_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PostPublic_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(await to_candid_CreatePostRequest_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PostPublic_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOptimizationResult(arg0: PostId): Promise<OptimizationResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOptimizationResult(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOptimizationResult(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: PostId): Promise<PostPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishResults(arg0: PostId): Promise<Array<PlatformResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishResults(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishResults(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listPosts(): Promise<Array<PostPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPosts();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPosts();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSocialAccounts(): Promise<Array<SocialAccountPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSocialAccounts();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSocialAccounts();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async optimizeCaption(arg0: PostId): Promise<OptimizationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.optimizeCaption(arg0);
                return from_candid_OptimizationResult_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.optimizeCaption(arg0);
            return from_candid_OptimizationResult_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async publishPost(arg0: PostId): Promise<Array<PlatformResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.publishPost(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishPost(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async revokeSocialAccount(arg0: AccountId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeSocialAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeSocialAccount(arg0);
            return result;
        }
    }
    async transformAi(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformAi(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformAi(arg0);
            return result;
        }
    }
    async transformPublish(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformPublish(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformPublish(arg0);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_OptimizationResult_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OptimizationResult): OptimizationResult {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_PlatformCaption_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlatformCaption): PlatformCaption {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_PlatformResult_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlatformResult): PlatformResult {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Platform_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Platform): Platform {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function from_candid_PostPublic_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostPublic): Promise<PostPublic> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_PublishStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublishStatus): PublishStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_SocialAccountPublic_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SocialAccountPublic): SocialAccountPublic {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OptimizationResult]): OptimizationResult | null {
    return value.length === 0 ? null : from_candid_OptimizationResult_n36(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PostPublic]): Promise<PostPublic | null> {
    return value.length === 0 ? null : await from_candid_PostPublic_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AccountId;
    createdAt: _Timestamp;
    platform: _Platform;
    isActive: boolean;
    accountHandle: string;
}): {
    id: AccountId;
    createdAt: Timestamp;
    platform: Platform;
    isActive: boolean;
    accountHandle: string;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        platform: from_candid_Platform_n14(_uploadFile, _downloadFile, value.platform),
        isActive: value.isActive,
        accountHandle: value.accountHandle
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PostId;
    mediaFilename: string;
    createdAt: _Timestamp;
    originalCaption: string;
    publishStatus: _PublishStatus;
    updatedAt: _Timestamp;
    mediaBlob: _ExternalBlob;
    platformResults: Array<_PlatformResult>;
    selectedPlatforms: Array<_Platform>;
}): Promise<{
    id: PostId;
    mediaFilename: string;
    createdAt: Timestamp;
    originalCaption: string;
    publishStatus: PublishStatus;
    updatedAt: Timestamp;
    mediaBlob: ExternalBlob;
    platformResults: Array<PlatformResult>;
    selectedPlatforms: Array<Platform>;
}> {
    return {
        id: value.id,
        mediaFilename: value.mediaFilename,
        createdAt: value.createdAt,
        originalCaption: value.originalCaption,
        publishStatus: from_candid_PublishStatus_n24(_uploadFile, _downloadFile, value.publishStatus),
        updatedAt: value.updatedAt,
        mediaBlob: await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value.mediaBlob),
        platformResults: from_candid_vec_n27(_uploadFile, _downloadFile, value.platformResults),
        selectedPlatforms: from_candid_vec_n32(_uploadFile, _downloadFile, value.selectedPlatforms)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PublishStatus;
    postUrl: [] | [string];
    publishedAt: [] | [_Timestamp];
    platform: _Platform;
}): {
    status: PublishStatus;
    postUrl?: string;
    publishedAt?: Timestamp;
    platform: Platform;
} {
    return {
        status: from_candid_PublishStatus_n24(_uploadFile, _downloadFile, value.status),
        postUrl: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.postUrl)),
        publishedAt: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.publishedAt)),
        platform: from_candid_Platform_n14(_uploadFile, _downloadFile, value.platform)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    suggestions: Array<_PlatformCaption>;
    generatedAt: _Timestamp;
    postId: _PostId;
}): {
    suggestions: Array<PlatformCaption>;
    generatedAt: Timestamp;
    postId: PostId;
} {
    return {
        suggestions: from_candid_vec_n38(_uploadFile, _downloadFile, value.suggestions),
        generatedAt: value.generatedAt,
        postId: value.postId
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hashtags: Array<string>;
    platform: _Platform;
    caption: string;
}): {
    hashtags: Array<string>;
    platform: Platform;
    caption: string;
} {
    return {
        hashtags: value.hashtags,
        platform: from_candid_Platform_n14(_uploadFile, _downloadFile, value.platform),
        caption: value.caption
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    linkedin: null;
} | {
    tiktok: null;
} | {
    twitter: null;
} | {
    instagram: null;
} | {
    facebook: null;
}): Platform {
    return "linkedin" in value ? Platform.linkedin : "tiktok" in value ? Platform.tiktok : "twitter" in value ? Platform.twitter : "instagram" in value ? Platform.instagram : "facebook" in value ? Platform.facebook : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    publishing: null;
} | {
    success: null;
} | {
    failed: string;
}): {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "publishing";
    publishing: null;
} | {
    __kind__: "success";
    success: null;
} | {
    __kind__: "failed";
    failed: string;
} {
    return "pending" in value ? {
        __kind__: "pending",
        pending: value.pending
    } : "publishing" in value ? {
        __kind__: "publishing",
        publishing: value.publishing
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlatformResult>): Array<PlatformResult> {
    return value.map((x)=>from_candid_PlatformResult_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Platform>): Array<Platform> {
    return value.map((x)=>from_candid_Platform_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlatformCaption>): Array<PlatformCaption> {
    return value.map((x)=>from_candid_PlatformCaption_n39(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PostPublic>): Promise<Array<PostPublic>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PostPublic_n22(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SocialAccountPublic>): Array<SocialAccountPublic> {
    return value.map((x)=>from_candid_SocialAccountPublic_n12(_uploadFile, _downloadFile, x));
}
function to_candid_AddAccountRequest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddAccountRequest): _AddAccountRequest {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_CreatePostRequest_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreatePostRequest): Promise<_CreatePostRequest> {
    return await to_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Platform_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): _Platform {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mediaFilename: string;
    originalCaption: string;
    mediaBlob: ExternalBlob;
    selectedPlatforms: Array<Platform>;
}): Promise<{
    mediaFilename: string;
    originalCaption: string;
    mediaBlob: _ExternalBlob;
    selectedPlatforms: Array<_Platform>;
}> {
    return {
        mediaFilename: value.mediaFilename,
        originalCaption: value.originalCaption,
        mediaBlob: await to_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.mediaBlob),
        selectedPlatforms: to_candid_vec_n21(_uploadFile, _downloadFile, value.selectedPlatforms)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    refreshToken: string;
    platform: Platform;
    accessToken: string;
    accountHandle: string;
}): {
    refreshToken: string;
    platform: _Platform;
    accessToken: string;
    accountHandle: string;
} {
    return {
        refreshToken: value.refreshToken,
        platform: to_candid_Platform_n10(_uploadFile, _downloadFile, value.platform),
        accessToken: value.accessToken,
        accountHandle: value.accountHandle
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): {
    linkedin: null;
} | {
    tiktok: null;
} | {
    twitter: null;
} | {
    instagram: null;
} | {
    facebook: null;
} {
    return value == Platform.linkedin ? {
        linkedin: null
    } : value == Platform.tiktok ? {
        tiktok: null
    } : value == Platform.twitter ? {
        twitter: null
    } : value == Platform.instagram ? {
        instagram: null
    } : value == Platform.facebook ? {
        facebook: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Platform>): Array<_Platform> {
    return value.map((x)=>to_candid_Platform_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
